Add types declaration file
raymond-lam/politely pull request #2
Opened 2020-12-21 10:41 UTC by geopic

Resolves #1. Let me know if there are any issues.

2020-12-22 05:44 UTC, raymond-lam requested changes

2020-12-22 05:44 UTC, raymond-lam commented on politely.d.ts
> +  logger: object;
Can we be more specific than `object` for `logger`?  `logger` should be an object with `info`, `warn`, and `error` methods. A Winston logger, for instance, would satisfy this requirement. It is also an optional argument.

2020-12-22 05:44 UTC, raymond-lam commented on politely.d.ts
> +  timeout: number;
timeout is an optional argument

2020-12-22 15:08 UTC, geopic commented on politely.d.ts
> +  timeout: number;
Noted

2020-12-22 15:19 UTC, geopic commented on politely.d.ts
> +  logger: object;
Noted :+1:

2020-12-22 15:42 UTC, raymond-lam requested changes

2020-12-22 15:42 UTC, raymond-lam commented on politely.d.ts
> +    error(message: string): void;
Although we only ever call `error`, `info` and `warn` with a single argument, a `winston` logger can accept a variable number of arguments. Will this be an issue in terms of static type checking?

2020-12-22 15:42 UTC, raymond-lam commented on politely.d.ts
> +    error(message: string): void;
(For that matter, I assume it will be okay if the logger that is passed in has these methods and more, right?)

2020-12-23 19:14 UTC, raymond-lam commented on politely.d.ts
> +    error(message: string): void;
I just tried it and it worked

2020-12-23 19:14 UTC, raymond-lam approved these changes

2020-12-23 19:14 UTC, merged